experiment_id: P3_TIDMAD_OPTIONAL
dataset: tidmad
enabled: false
upstream_repository: https://github.com/jessicafry/TIDMAD
data_root: /ceph/dwong/paper1_dataset
dataset_dir: /ceph/dwong/paper1_dataset/tidmad
raw_data_dir: /ceph/dwong/paper1_dataset/tidmad/raw
processed_data_dir: /ceph/dwong/paper1_dataset/tidmad/processed
