LCE: '/kalinka/storage/darkmatter/DELight/share/TraceSimulator/optical/optSim_LCE.npz'
optArrivalTime: '/kalinka/storage/darkmatter/DELight/share/TraceSimulator/optical/optSim_arrivalTime.npz'
PCE: '/kalinka/storage/darkmatter/DELight/share/TraceSimulator/acoustic/phonSim_PCE.npz'
phonArrivalTime: '/kalinka/storage/darkmatter/DELight/share/TraceSimulator/acoustic/phonSim_phonTemplate.npz'
TCE: '/kalinka/storage/darkmatter/DELight/share/TraceSimulator/triplet/trSim_TCE.npz'
trArrivalTime: '/kalinka/storage/darkmatter/DELight/share/TraceSimulator/triplet/trSim_trTemplate.npz'
positionMMC: '/kalinka/storage/darkmatter/DELight/share/TraceSimulator/position_MMC.dat'
sampling_frequency: 250000.0
trace_samples: 16384
noise_type: 'pink'
